# Generated by Django 4.1.5 on 2023-03-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PersonalDataAdmin", "0003_alter_personaldata_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaldata",
            name="date_of_birth",
            field=models.DateTimeField(),
        ),
    ]
