# Generated by Django 4.1.5 on 2023-03-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PersonalDataAdmin", "0006_personaldata_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="dekan_remarks",
            field=models.TextField(default=""),
        ),
    ]
