# Generated by Django 4.1.5 on 2023-03-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PersonalDataAdmin", "0007_student_dekan_remarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Kierunek studiów",
                "verbose_name_plural": "Kierunki studiów",
            },
        ),
        migrations.AddField(
            model_name="student",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="PersonalDataAdmin.course",
            ),
        ),
    ]
