# Generated by Django 4.1.5 on 2023-03-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PersonalDataAdmin", "0011_alter_student_dekan_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personaldata",
            name="remarks",
            field=models.TextField(default="aktualnie brak"),
        ),
    ]
