# Generated by Django 4.1.5 on 2023-03-07 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("PersonalDataAdmin", "0007_student_dekan_remarks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("note", models.TextField()),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="PersonalDataAdmin.personaldata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notatka",
                "verbose_name_plural": "Notatki",
            },
        ),
    ]
