# Generated by Django 4.1.5 on 2023-03-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notes", "0002_remove_note_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="create_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
