# Generated by Django 4.1.5 on 2023-03-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notes", "0003_alter_note_create_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="create_date",
            field=models.DateTimeField(),
        ),
    ]
